# --- Build stage ---
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .

# Solo se inyectan valores VITE_*, que por definición terminan en el bundle
# público. Los secretos server-side de .env nunca entran en el contexto Docker.
ARG VITE_SUPABASE_PROJECT_ID
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_URL
ARG VITE_AGROIRIS_API_URL
ARG VITE_AGROIRIS_LOGIN_URL
ARG VITE_AGROIRIS_CUENTAVENTA_API_URL
ARG VITE_AGROIRIS_CUENTAVENTA_LOGIN_URL
ARG VITE_AGROIRIS_LOGIN
ARG VITE_AGROIRIS_PASSWORD

ENV VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID \
    VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY \
    VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_AGROIRIS_API_URL=$VITE_AGROIRIS_API_URL \
    VITE_AGROIRIS_LOGIN_URL=$VITE_AGROIRIS_LOGIN_URL \
    VITE_AGROIRIS_CUENTAVENTA_API_URL=$VITE_AGROIRIS_CUENTAVENTA_API_URL \
    VITE_AGROIRIS_CUENTAVENTA_LOGIN_URL=$VITE_AGROIRIS_CUENTAVENTA_LOGIN_URL \
    VITE_AGROIRIS_LOGIN=$VITE_AGROIRIS_LOGIN \
    VITE_AGROIRIS_PASSWORD=$VITE_AGROIRIS_PASSWORD

RUN npm run build

# --- Runtime stage ---
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
