services:
  agroiris:
    build:
      context: .
      args:
        VITE_SUPABASE_PROJECT_ID: ${VITE_SUPABASE_PROJECT_ID}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_AGROIRIS_API_URL: ${VITE_AGROIRIS_API_URL}
        VITE_AGROIRIS_LOGIN_URL: ${VITE_AGROIRIS_LOGIN_URL}
        VITE_AGROIRIS_CUENTAVENTA_API_URL: ${VITE_AGROIRIS_CUENTAVENTA_API_URL}
        VITE_AGROIRIS_CUENTAVENTA_LOGIN_URL: ${VITE_AGROIRIS_CUENTAVENTA_LOGIN_URL}
        VITE_AGROIRIS_LOGIN: ${VITE_AGROIRIS_LOGIN}
        VITE_AGROIRIS_PASSWORD: ${VITE_AGROIRIS_PASSWORD}
    container_name: campojoyma
    restart: unless-stopped
    ports:
      - "8080:80"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
