create table if not exists public.cuentaventa_errores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  archivo_pdf_id bigint references public.archivos_pdf(id) on delete cascade,
  codigo text not null,
  mensaje text not null,
  numero_pagina integer,
  raw_payload jsonb
);

create index if not exists cuentaventa_errores_archivo_pdf_id_idx on public.cuentaventa_errores (archivo_pdf_id);
create index if not exists cuentaventa_errores_created_at_idx on public.cuentaventa_errores (created_at desc);

alter table public.cuentaventa_errores enable row level security;

drop policy if exists "Cuentaventa_errores: select visibles" on public.cuentaventa_errores;
create policy "Cuentaventa_errores: select visibles"
on public.cuentaventa_errores
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.cuentaventas cv
    where cv.archivo_pdf_id = cuentaventa_errores.archivo_pdf_id
      and public.is_cliente_visible(cv.clienteid)
  )
);

drop policy if exists "Cuentaventa_errores: delete admin" on public.cuentaventa_errores;
create policy "Cuentaventa_errores: delete admin"
on public.cuentaventa_errores
for delete
to authenticated
using (public.is_admin());
