create table if not exists public.user_access_logs (
  id bigint not null,
  created_at timestamptz not null default now(),
  user_id uuid not null,
  email text,
  action text not null check (action in ('login', 'logout')),
  metadata jsonb
);

alter table public.user_access_logs
  alter column id add generated by default as identity (sequence name public.user_access_logs_id_seq);

create index if not exists user_access_logs_created_at_idx
  on public.user_access_logs (created_at desc);

create index if not exists user_access_logs_user_id_idx
  on public.user_access_logs (user_id);

alter table public.user_access_logs enable row level security;

drop policy if exists "User access logs: insert self" on public.user_access_logs;
create policy "User access logs: insert self"
on public.user_access_logs
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "User access logs: select admins" on public.user_access_logs;
create policy "User access logs: select admins"
on public.user_access_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid()
      and ur.role = 'admin'
  )
);
